### ISSUE TITLE
Rückschlagventile

### ISSUE THREAD

**Issue by auenkind** [auenkind/YACoVV#3]
Der Druckregler braucht 3 Rückschlagventile an den Wassersäulen so das kein Wasser in das System gelangen kann.

**Comment by dachdecker2** [comment]
Könnte es helfen, statt einem Rückschlagventil eine Druckbegrenzung nach unten einzubauen?

Mein Vorschlag ist, einen zweiten Wasserbehälter (links im Bild) - invers zum ersten angeschlossen (rechts im Bild) - zu benutzen:
 - der Patient ist über der Wasseroberfläche angeschlossen (Wie der CO2-Absorber im bestehenden Teil des Systems)
 - Umgebungsluft ist am im Wasser steckenden Schlauch angeschlossen

Die Eintauchtiefe bestimmt den Mindestdruck - der sollte unter p_a liegen. 
Der Schlauch zur Umgebungsluft müsste außerdem lang (bzw. hoch) genug sein, damit das Wasser nicht aus dem Behälter gedrückt werden kann - d.h. mehr als die Eintauchtiefe p_i (oder gleich > 50 mbar).

![Rueckschlagventilersatz](https://user-images.githubusercontent.com/3836508/77819958-1aed5200-70df-11ea-8b76-93d760189531.gif)

**Comment by GRRTK** [comment]
Kann man Rückschlagventile aus der Aquaristik nehmen? z.B. [das hier](https://www.interaquaristik.de/aquascaping/glaswaren/co2-zubehoer/orinocoglass-check-valve-rueckschlagventil-aus-glas/a-83653) oder [das hier](https://www.koigarten-mueller.de/Luft-Rueckschlagventile-4mm-mit-Membrane)?

**Comment by Pixtxa** [comment]
Könnte man so evtl. ein Ventil einsparen? Wenn da hinten dran Wasser ist, kann das ja eh nur wieder abfließen, welchen Weg es nimmt, dürfte egal sein.
Das Ventil fürs Manometer würde ich nicht auch so einsparen, da es den Messwert verfälschen würde, wenn dort Wasser hineinfließt oder herausgesaugt wird.
![Screenshot_20200329_043327](https://user-images.githubusercontent.com/30337073/77838757-0361a800-7177-11ea-914b-e75fbb08f565.jpg)

Alternativ müsste sich aber auch ein Behälter mit eingetauchtem Schlauch (Patient wird an abgedichteten Deckel des Gefäßes angeschlossen) als Unterdruck-Ventil verwenden lassen. Da dieses dann sofort Luft einströmen lässt, falls der Patient beim Husten einatmet, kann die Wassersäule in den anderen Schläuchen nicht so weit steigen, dass sie gefährlich werden könnte.
![Screenshot_20200329_050353](https://user-images.githubusercontent.com/30337073/77839168-b97ac100-717a-11ea-930b-836886c852d7.jpg)

**Comment by auenkind** [comment]
> 
> 
> Kann man Rückschlagventile aus der Aquaristik nehmen? z.B. [das hier](https://www.interaquaristik.de/aquascaping/glaswaren/co2-zubehoer/orinocoglass-check-valve-rueckschlagventil-aus-glas/a-83653) oder [das hier](https://www.koigarten-mueller.de/Luft-Rueckschlagventile-4mm-mit-Membrane)?



> 
> 
> Kann man Rückschlagventile aus der Aquaristik nehmen? z.B. [das hier](https://www.interaquaristik.de/aquascaping/glaswaren/co2-zubehoer/orinocoglass-check-valve-rueckschlagventil-aus-glas/a-83653) oder [das hier](https://www.koigarten-mueller.de/Luft-Rueckschlagventile-4mm-mit-Membrane)?

Das ist grundsätzlich das richtige Ventilprinzip, die Aquaristik-Ventile haben aber einen deutlich zu kleinen Durchmesser um die benötigte Durchflussmenge / Zeit zu erreichen.

**Comment by auenkind** [comment]
> 
> 
> Könnte es helfen, statt einem Rückschlagventil eine Druckbegrenzung nach unten einzubauen?
> 
> Mein Vorschlag ist, einen zweiten Wasserbehälter (links im Bild) - invers zum ersten angeschlossen (rechts im Bild) - zu benutzen:
> 
>     * der Patient ist über der Wasseroberfläche angeschlossen (Wie der CO2-Absorber im bestehenden Teil des Systems)
> 
>     * Umgebungsluft ist am im Wasser steckenden Schlauch angeschlossen
> 
> 
> Die Eintauchtiefe bestimmt den Mindestdruck - der sollte unter p_a liegen.
> Der Schlauch zur Umgebungsluft müsste außerdem lang (bzw. hoch) genug sein, damit das Wasser nicht aus dem Behälter gedrückt werden kann - d.h. mehr als die Eintauchtiefe p_i (oder gleich > 50 mbar).
> 
> ![Rueckschlagventilersatz](https://user-images.githubusercontent.com/3836508/77819958-1aed5200-70df-11ea-8b76-93d760189531.gif)
> 
> Nachtrag:
> der Vorschlag hätte folgende Vorteile gegenüber Rückschlagventilen:
> 
>     * spontanes Einatmen wird nicht übermäßig behindert
> 
>     * weiterhin keine verschleisbehafteten/verhaltensbeeinflussenden Teile
> 
> 
> richtige Rückschlagventile kann man vielleicht zusätzlich einbauen, diese machen das Systemverhalten aber wahrscheinlich komplizierter:
> 
>     * Öffnungsverhalten und zusätzlicher ggf. nich konstanter Druckabfall über den Ventilmechanismus
> 
>     * Verhaltensänderung bei Benetzung mit Wasser

Das ist eine sehr gute Überlegung. Bedenken muss man dabei noch die verhältnismäßig große Volumensteigerung des Überdrucksystems durch den "Hohlraum" im zweiten Behälter.

**Comment by dachdecker2** [comment]
Man müsste mal probieren, ob das zusätzliche Luftvolumen wirklich groß sein muss. Intuitiv hätte ich z.B. das Luftvolumen im Video gezeigten Glasbalon sehr viel größer gemacht - offensichtlich funktioniert es aber auch mit dem Volumen << 1 l schon.
"Worst-Case-Betrachtung":
Der Druck im System kann sich eigentlich nicht um mehr als 50 mbar ändern - das sind etwa 5% des Luftdrucks. Nach Wikipedia soll das Tidalvolumen ~0,5 l sein. Wenn Die Regelung keine Schwierigkeiten mit dem größeren Volumen in Schlauch und "Ventil" hat, ergibt sich ein Verlust an bis zu 20% des bereitgestellten Gases unter folgenden Annahmen:
- Ventilvolumen: 1 l
- Schlauchvolumen: 1 l
- Druckänderung zwischen Ein- und Ausatmen: bis zu 50 mbar
- Umgebungsdruck: 1000 mbar
- Tidalvolumen: 0,5 l
- Gasverlust = Umgebungsdruck * Tidalvolumen / (Druckänderung * (Ventilvolumen + Schlauchvolumen) ) = 0,2

Angesichts des überaschend kleinen Tidalvolumens würde ich als Gegenvorschlag zur Elimination eines Ventils (@Pixtxa) die Veringerung des Totvolumens vorschlagen (siehe Bild), damit die angeschlossene Person weniger ausgeatmete Luft zurückbekommt.
![Rueckschlagventilersatz2](https://user-images.githubusercontent.com/3836508/77861356-bb915e00-7214-11ea-9a57-eab599d56221.png)

**Comment by auenkind** [comment]
@dachdecker2 deine letzte Zeichnung ist eine wirklich gute Lösung, ich werde das so in die Zeichnungen übernehmen. Zusätzlich dazu können wird dann unser Schlauchmanometer einsparen. Denn der Druck wird an der Wassersäule angezeigt die im linken Schlauch des neuen Wassergefäßes steht. Nebenbei ergibt sich noch der Vorteil das diese Wassersäule doppelt so hoch steigt wie die im bisherigen Aufbau und dadurch besser abzulesen ist.

**Comment by auenkind** [comment]
würde in etwa so aussehen:

![infogfx_changes](https://user-images.githubusercontent.com/13538227/77882566-85c69680-7261-11ea-9af2-22baef322b6a.jpg)

**Comment by sneu14** [comment]
ich denke auch das diese Lösung als Unterdruckventil funktioniert. Ob man das auch als Manometer verwenden kann müsste man testen. Durch das zusätzliche Luftvolumen in dem Behälter könnte die Anzeige etwas mehr schwingen wie wenn es direkt angeschlossen ist. Das sollten wir aber auf jeden Fall testen

**Comment by dachdecker2** [comment]
@auenkind, @Pixtxa : genau so habe ich das gemeint. Was meint Ihr zum Totvolumen im Schlauch? Wie groß ist das im Video gezeigte Tidalvolumen?

**Comment by sneu14** [comment]
Zum Totavolumen sollten wir uns mal die Hardware anschauen die unmittelbar am Patienten verwendet wird. Im besten Falle würden man 2 Schläuche bis unmittelbar zum Patienten legen. Dann haben wir in den Leitungen den Luftstrom immer nur in einer Richtung, andererseits erhöhen wir dadmit das Volumen des gesamten Systems und müssen viel mehr Luft reinblasen um den Druck zu erreichen. Ich denke wir müssen uns dort an den Beatmungsgarnituren orienteiern die verfügbar sind auch verwendet werden würden und diese so nah wie möglich an unserem System anschliessen.

**Comment by auenkind** [comment]
ich schließe das, denn die aktuell Rückschlagventil Lösung erscheint mir brauchbar. Wenn es im Test nicht klappen sollte mache ich das Ticket wieder auf,
